research_task:
  description: >
    Conduct a thorough research to answer a customers question: "{question}"
    Make sure you find any relevant information and present it in the best possible way
    for the customer to understand
  expected_output: >
    Costumer Service message as a response to the given inquiry based on the research from the given company document
  agent: researcher


writer_task:
  description: >
    Write a response to the customer's inquiry: "{question}"
    Make sure you include all the relevant information and present it in a friendly way
    that is concicse and BRIEF
  expected_output: >
    A response to the {question} in the form of an answer from a customer service agent
  agent: writer