research_task:
  description: >
    Conduct a thorough research to answer a customers question: "{question}"
    Make sure you find any relevant information and present it in the best possible way
    for the customer to understand
  expected_output: >
    Costumer Service message as a response to the given inquiry based on the research from the given company document
  agent: researcher
